title: Saxamos
logo:  # you can add own logo.
description: Personnal blog of Samuel, Data & Computer Science enthusiast (Machine Learning and Uncertainty),
  also Saxophonist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://saxamos.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Samuel Rochette
  image: "/assets/img/sam.png"
  job: ⚜️ Data Scientist ⚜️
  bio: I am a data scientist focused on modeling and uncertainty ¯\_(ツ)_/¯‍
  email: samuel.rochette06@gmail.com


# Contact links
contact:
  - name: Twitter
    link: https://twitter.com/Sasamos
  - name: Facebook
    link: https://facebook.com/srochette
  - name: Instagram
    link: https://instagram.com/sasamos
  - name: Github
    link: https://github.com/Saxamos
  - name: linkedin
    link: https://www.linkedin.com/in/samuelrochette/?locale=en_US


disqus-identifier: samuel_rochette
google-analytics: UA-164062586-1


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-seo-tag


# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
