title: Saxamos
description:
  Personnal blog of Samuel, Data & Computer Science enthusiast, also Saxophonist.
permalink: ':title/'
baseurl: ""
url: "https://saxamos.github.io/"
site-twitter: Sasamos

# Author Settings
author: Samuel Rochette
author-img: sam.png
about-author: I am a data scientist focused on modeling and uncertainty. Always hungry to keep learning.
social-twitter: Sasamos
social-facebook: srochette
social-github: Saxamos
social-linkedin: samuelrochette/?locale=en_US
social-email: samuel.rochette06@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
